### ISSUE TITLE
Please set a license for this repo

### ISSUE THREAD

**Issue by vitaly-zdanevich** [MrPenguin07/ebuilds#2]

**Comment by MrPenguin07** [comment]
Done dd01be9

**Comment by vitaly-zdanevich** [comment]
Hi, is it ok if I copy your ebuild to Guru? https://github.com/gentoo/guru/commit/7a33665aae8f672c7013b6e1939eece68f77b3af#commitcomment-143499277

**Comment by MrPenguin07** [comment]
> Hi, is it ok if I copy your ebuild to Guru? [gentoo/guru@7a33665#commitcomment-143499277](https://github.com/gentoo/guru/commit/7a33665aae8f672c7013b6e1939eece68f77b3af#commitcomment-143499277)

Yes that's ok to be copied to Guru.
Some fixes were made which I've back ported so all good.
