### ISSUE TITLE
upscayl-9999 fails to compile since commit b22aa99bd630be4f62a4f065559be6de847fb815

### ISSUE THREAD

**Issue by SigHunter** [MrPenguin07/ebuilds#7]
Hi, thank you very much for the ebuilds for upscayl!

Recently, latest upscayl-9999 started to fail. Compiling works up until commit [f1be357f8ac3e36aef382b610a89b0567953645b](https://github.com/upscayl/upscayl/commit/f1be357f8ac3e36aef382b610a89b0567953645b) and starts to fail beginning with [b22aa99bd630be4f62a4f065559be6de847fb815](https://github.com/upscayl/upscayl/commit/b22aa99bd630be4f62a4f065559be6de847fb815)

Full build log attached

[buildlog.txt](https://github.com/user-attachments/files/16735935/buildlog.txt)

> ▲ Next.js 14.1.1
>    - Experiments (use at your own risk):
>      · externalDir
> 
>    Linting and checking validity of types  ...Failed to compile.
> 
> ./components/upscayl-tab/view/ProgressBar.tsx:34:65
> Type error: Type '{ "--value": number; }' is not assignable to type 'Properties<string | number, string & {}>'.
>   Object literal may only specify known properties, and '"--value"' does not exist in type 'Properties<string | number, string & {}>'.
> 
>   32 |         </p>
>   33 |         {progress !== "Hold on..." ? (
> > 34 |           <div className33m="radial-progress text-center" style33m={{ "--value": parseFloat(progress.replace("%", '')) }} role33m="progressbar" aria-valuenow33m={ parseFloat(progress.replace("%", '')) } aria-valuemin33m="0" aria-valuemax33m="100">
>      |                                                                 ^
>   35 |             {progress}
>   36 |             {!batchMode && (doubleUpscaylCounter > 0) && "\nPass " + doubleUpscaylCounter}
>   37 |           </div>
> >>> Source compiled.
> >>> Test phase [not enabled]: media-gfx/upscayl-9999
> 
> >>> Install media-gfx/upscayl-9999 into /var/tmp/portage/media-gfx/upscayl-9999/image
> find: ‘/var/tmp/portage/media-gfx/upscayl-9999/work/upscayl-9999/dist/’: No such file or directory
>

**Comment by MrPenguin07** [comment]
Hi,

Thanks for reporting, and being specific which commit it began to fail at.
I've confirmed as such as will dig into it when I can.

Appreciate knowing others value the ebuilds.

**Comment by SigHunter** [comment]
not sure who or what fixed it but it works now! maybe the issue was upstream and not the ebuild after all? I successfully built 356bb5cf95c255914c66ea6d822473f576b0c844. thanks anyways for providing the ebuild :-)
