### ISSUE TITLE
dev-ml category misused

### ISSUE THREAD

**Issue by xgqt** [MrPenguin07/ebuilds#8]
Hello!

Historically the dev-ml category in ::gentoo is used for Oca**ml** packages.

Please migrate to some other descriptive category for AI/Machine Learning tools.
I'd propose `dev-util`, `app-misc` (as classified by Gentoo) or `app-ai`, `dev-ai` (custom category).

Thanks in advance.

**Comment by MrPenguin07** [comment]
Hi. 

Yes this has indeed been raised before, and discussed on guru where my ebuild was taken and relicensed.
I thank you for your attention to detail however I've already decided to wait until Gentoo creates a proper AI category.
"app-misc" etc are vague and silly. Creating custom categories brings portage errors, it would require all users of this overlay to add the category manually.

At least the abbreviated form of dev-ml makes sense.

> > There are no "AI" categories in gentoo

This is the underlying problem. Gentoo have been slow to realize that AI apps are the hottest thing in the past few years are are lagging behind. If I may, I would suggest as a developer to push for the creation of one, the need is there - as evidenced by the multiple repos you've lodged issues against for this issue.

Thank you.

**Comment by xgqt** [comment]
> Creating custom categories brings portage errors, it would require all users of this overlay to add the category manually.

That is not true. See this: 
* https://gitlab.com/xgqt/myov/-/commit/4f0a97f4dc11efd15a226b4993d6bab12dc4a710
* https://gitlab.com/xgqt/myov/-/commit/7eae4832596646093f713bd46822e79660c94f2a

**Comment by MrPenguin07** [comment]
> > Creating custom categories brings portage errors, it would require all users of this overlay to add the category manually.
> 
> That is not true. See this:

Upon further testing, you are correct. 
Portage does however throw the following error, a partially correct red herring stating the change should be in /etc/portage:
```
Calculating dependencies -
!!! 'app-ai/ollama' has a category that is not listed in /etc/portage/categories
```
I'm sure it's documented _somewhere_.  
In any case I believe Gentoo should be who takes this on - officially, otherwise I'll have to move it **again** if/when an official category is made.
